### ISSUE TITLE
hedera testnet is unavailable, throwing 503. how to check status of hedera testnet?

### ISSUE THREAD

**Issue by vijayshiyani** [hashgraph/did-sdk-java#18]
Please ask questions you have in our [Discord](https://discordapp.com/invite/FFb9YFX) group first. You can also search GitHub to see if the issue has been reported already.

Otherwise, please feel free to ask your question here.
`2021-11-16 14:51:30:999 INFO AppnetServer - Starting appnet API server...
2021-11-16 14:51:31:001 INFO AppnetServer - Initializing identity network...
2021-11-16 14:51:31:766 INFO AppnetServer - Setting up new identity network...
2021-11-16 14:51:36:580 ERROR Executable - caught error, retrying
node=0.0.6
attempt=1
{}
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503
invalid content-type: text/html
headers: Metadata(:status=503,content-length=107,cache-control=no-cache,content-type=text/html)
DATA-----------------------------
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

DATA-----------------------------

	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by vijayshiyani** [comment]
https://status.hedera.com/
