### ISSUE TITLE
problem running examples/appnet-api-server

### ISSUE THREAD

**Issue by paliwalg** [hashgraph/did-sdk-java#5]
Trying to run the example on windows 10 machine.

Not able to start the AppnetServer, failing with below error :

2020-06-07 18:13:11:040 INFO AppnetServer - Setting up new identity network...
2020-06-07 18:13:12:518 ERROR AppnetServer - Error during startup:
com.hedera.hashgraph.sdk.HederaPrecheckStatusException: transaction 0.0.7472@1591533781.238000000 failed precheck with status TRANSACTION_EXPIRED
        at com.hedera.hashgraph.sdk.HederaPrecheckStatusException.throwIfExceptional(HederaPrecheckStatusException.java:23)
        at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:272)
        at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:33)
        at com.hedera.hashgraph.sdk.HederaCall.lambda$execute$0(HederaCall.java:55)
        at com.hedera.hashgraph.sdk.Backoff.tryWhile(Backoff.java:37)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:58)
        at com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:132)
        at com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:33)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:44)
        at com.hedera.hashgraph.identity.hcs.HcsIdentityNetworkBuilder.execute(HcsIdentityNetworkBuilder.java:47)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.setupIdentityNetwork(AppnetServer.java:347)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.initHederaIdentityNetwork(AppnetServer.java:296)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.startUp(AppnetServer.java:83)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.main(AppnetServer.java:68)
2020-06-07 18:13:12:524 INFO AppnetServer - Shutting down appnet API server...
2020-06-07 18:13:12:535 ERROR AppnetServer - Error during shutdown:
java.util.concurrent.TimeoutException: Timed out waiting for node channel to shutdown: 0.0.5 :: 2.testnet.hedera.com:50211
        at com.hedera.hashgraph.sdk.Node.awaitChannelTermination(Node.java:55)
        at com.hedera.hashgraph.sdk.Client.close(Client.java:450)
        at com.hedera.hashgraph.sdk.Client.close(Client.java:418)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.shutDown(AppnetServer.java:247)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer.access$000(AppnetServer.java:41)
        at com.hedera.hashgraph.identity.hcs.example.appnet.AppnetServer$1.run(AppnetServer.java:78)
2020-06-07 18:13:12:536 INFO AppnetServer - Appnet API server stopped.

**Comment by paliwalg** [comment]
Got it working , it was because of host system datetime issue
