### ISSUE TITLE
Starting example appnet throws an error

### ISSUE THREAD

**Issue by suresh12** [hashgraph/did-sdk-java#6]
**Problem**
Hi, I am trying to run the example from new identity sdk did-sdk-java. 
When I am running 'gradle :appnet-api-server:run', I am getting the following error,

`io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: com.hedera.mirror.api.proto.ConsensusService/subscribeTopic`

Is this a known issue?

**Environment:**
- Java: OpenJDK 11
- OS: Mac OSX v10.14

**Additional Context**
Complete error log as follows,
```
2020-06-07 16:22:25:971 ERROR AppnetServer - Error while processing message from VC topic:
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: com.hedera.mirror.api.proto.ConsensusService/subscribeTopic
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by suresh12** [comment]
Closing the issue as it was a spelling mistake in the mirror node configuration.
